---
version: "3.7"
services:

  # ---------------------------------------------------------------------
  # | Natours - Nginx-Service                                                     |
  # ---------------------------------------------------------------------
  natours:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: natours
    image: paulserbandev/natours
    restart: unless-stopped
    volumes:
      # Mounts the nginx configuration file
      # the section after collon is the path inside the container, do not chenge it if you don't know what you are doing
      - ./dist:/usr/share/nginx/html
      - ../../assets/dist:/usr/share/nginx/html/assets
    labels:
      - traefik.enable=true
      # Routers
      - traefik.http.routers.nginx-natours.entrypoints=web
      - traefik.http.routers.nginx-natours.middlewares=test-redirectscheme

      - traefik.http.routers.nginx-natours.rule=Host(`natours.localhost`)
      - traefik.http.routers.nginx-natours-secure.rule=Host(`natours.localhost`)

      - traefik.http.routers.nginx-natours-secure.entrypoints=websecure
      - traefik.http.routers.nginx-natours-secure.tls=true
      - traefik.http.routers.nginx-natours-secure.middlewares=test-compress,test-redirectscheme
      # Services
      - traefik.http.services.nginx-natours-secure.loadbalancer.server.port=80
      # Middlewares
      - traefik.http.middlewares.test-compress.compress=true
      - traefik.http.middlewares.test-ratelimit.ratelimit.average=100
      - traefik.http.middlewares.test-ratelimit.ratelimit.burst=100
      - traefik.http.middlewares.test-ratelimit.ratelimit.period=1s
      - traefik.http.middlewares.test-redirectscheme.redirectscheme.scheme=https
      - traefik.http.middlewares.test-redirectscheme.redirectscheme.permanent=true
      - traefik.http.middlewares.test-redirectscheme.redirectscheme.port=443
